#!/usr/bin/env python
import csv,json
from pathlib import Path
import matplotlib.pyplot as plt

O=Path('dual_branch_outputs/p8_diagnosis');P=Path('dual_branch_outputs/p7_downstream')
load=lambda p:json.loads(Path(p).read_text())
raw=load(P/'p7_raw_metrics.json');inter=load(O/'p8_interpolation_downstream.json');geom=load(O/'p8_interpolation_results.json')['representation'];proj=load(O/'p8_projector_diagnostics.json');bootc=load(O/'p8_bootstrap_caption.json');bootg=load(O/'p8_bootstrap_grounding.json');bootr=load(O/'p8_bootstrap_rsa.json');hard=load(O/'p8_hard_retrieval.json');audit=load(O/'p8_real_random_audit.json');sample=load(O/'p8_sample_level_analysis.json')
variants=('lora','full_real','full_random');p7name={'lora':'lora','full_real':'full_real','full_random':'full_random'};rows=[]
for v in variants:
 for a in (0,.25,.5,.75,1):
  if a==0:c=raw['caption_metrics']['umbrae'];g=raw['grounding_metrics']['umbrae']
  elif a==1:c=raw['caption_metrics'][p7name[v]];g=raw['grounding_metrics'][p7name[v]]
  else:c=next(x for x in inter['caption'] if x['variant']==v and x['alpha']==a);g=next(x for x in inter['grounding'] if x['variant']==v and x['alpha']==a)
  r=next(x for x in geom if x['variant']==v and x['alpha']==a)
  rows.append({'variant':v,'alpha':a,'RSA':r['brain_rsa']['spearman_rsa'],'variant_to_base_cosine':r['variant_to_base_cosine'],'feature_norm_ratio':r['feature_norm_ratio_to_base'],'CIDEr':c['CIDEr'],'BLEU-4':c['BLEU-4'],'ROUGE-L':c['ROUGE-L'],'Mean_IoU':g['mean_iou'],'Grounding_Accuracy':g['grounding_accuracy'],'parse_failures':g['parse_failures']})
for name,fields in [('caption',['variant','alpha','CIDEr','BLEU-4','ROUGE-L']),('grounding',['variant','alpha','Mean_IoU','Grounding_Accuracy','parse_failures']),('geometry_utility',list(rows[0]))]:
 with (O/f'p8_interpolation_{name}.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows([{k:x[k] for k in fields} for x in rows])
(O/'p8_geometry_utility.csv').write_text((O/'p8_interpolation_geometry_utility.csv').read_text())
colors={'lora':'C0','full_real':'C1','full_random':'C2'}
def plot(name,xkey,ykeys,xlabel):
 plt.figure(figsize=(6,4))
 for v in variants:
  q=[x for x in rows if x['variant']==v]
  for y in ykeys:plt.plot([x[xkey] for x in q],[x[y] for x in q],marker='o',label=f'{v} {y}')
 plt.xlabel(xlabel);plt.legend(fontsize=7);plt.tight_layout();plt.savefig(O/name,dpi=160);plt.close()
plot('rsa_vs_cider.png','RSA',['CIDEr'],'RSA');plot('rsa_vs_grounding_acc.png','RSA',['Grounding_Accuracy'],'RSA');plot('alpha_vs_cider.png','alpha',['CIDEr'],'alpha');plot('alpha_vs_rsa.png','alpha',['RSA'],'alpha');plot('alpha_vs_grounding.png','alpha',['Mean_IoU','Grounding_Accuracy'],'alpha')
plt.figure(figsize=(6,4));x=range(3);plt.bar([i-.18 for i in x],[proj['modes'][v]['relative_l2_drift_brain'] for v in variants],.36,label='brain');plt.bar([i+.18 for i in x],[proj['modes'][v]['relative_l2_drift_projected'] for v in variants],.36,label='projected');plt.xticks(x,variants);plt.legend();plt.tight_layout();plt.savefig(O/'projector_drift_comparison.png',dpi=160);plt.close()
plt.figure(figsize=(6,4));plt.bar(range(4),[hard['models'][m]['recall_at_1'] for m in ('umbrae',*variants)]);plt.xticks(range(4),('umbrae',*variants),rotation=15);plt.ylabel('Hard R@1');plt.tight_layout();plt.savefig(O/'hard_retrieval_comparison.png',dpi=160);plt.close()
best=max(rows,key=lambda x:x['CIDEr']);summary={'P8_DIAGNOSIS':'OVER_CALIBRATION','CALIBRATION_DIRECTION':'PROMISING','CURRENT_CALIBRATION_STRENGTH':'TOO_STRONG','ANATOMICAL_SIGNAL':'DIRECTIONAL_ONLY','NEXT_STAGE':'P9_PRESERVATION_CONSTRAINED_CALIBRATION','P9_RECOMMENDATION':'A_STRONGER_PRESERVATION_PLUS_C_WEAKER_FUSION_AND_D_PROJECTOR_AWARE_PRESERVATION','sweet_spot':best,'projector_amplification':{v:proj['modes'][v]['amplification_ratio'] for v in variants},'projector_interface_mismatch':False,'geometry_survives_projector':True,'hard_retrieval':{m:{k:hard['models'][m][k] for k in ('recall_at_1','recall_at_5','recall_at_10','mrr','median_rank')} for m in ('umbrae',*variants)},'real_random_capacity_match':audit['REAL_RANDOM_CAPACITY_MATCH'],'random_control_limitation':audit['RANDOM_CONTROL_LIMITATION'],'bootstrap_caption_real_random':bootc['comparisons']['full_real_minus_full_random'],'bootstrap_grounding_real_random':bootg['comparisons']['full_real_minus_full_random'],'P8_STATUS':'COMPLETE','NEW_TRAINING_STARTED':False,'PARCEL_STAGE_STARTED':False,'PRF_STAGE_STARTED':False,'RETINOTOPY_STAGE_STARTED':False}
(O/'p8_summary.json').write_text(json.dumps(summary,indent=2)+'\n')
report=f'''# P8 Downstream-Compatible Structural Calibration Diagnosis\n\n## 1. Setup\nLocked test, 982 images and 2,419 grounding queries; frozen P7 checkpoints, mm_projector and Shikra. Alpha grid: 0, .25, .5, .75, 1.\n\n## 2. Statistical Validation\n10,000 paired caption, cluster-grounding and stimulus-RSA bootstraps. Real-Random CIs cross zero for all primary downstream metrics; anatomical evidence is directional only.\n\n## 3. Geometry–Utility Interpolation\nFull Real alpha=.25 is the CIDEr sweet spot: CIDEr {best['CIDEr']:.6f}, BLEU-4 {best['BLEU-4']:.6f}, grounding accuracy {best['Grounding_Accuracy']:.6f}, RSA {best['RSA']:.6f}. It improves alpha=1 and preserves/improves key baseline utilities. Diagnosis: over-calibration.\n\n## 4. Projector Interface Diagnostics\nAmplification ratios are {summary['projector_amplification']}. RSA gains persist after projection; no strong decoder-interface amplification evidence.\n\n## 5. Hard Retrieval\nK=99 hard negatives remove R@1 saturation. Full models improve median rank from 8 to 7; Real and Random remain close.\n\n## 6. Real vs Random Evidence\nArchitectural capacity and group sizes match, but checkpoint epochs differ and only one random seed exists. REAL_RANDOM_CAPACITY_MATCH = FAIL.\n\n## 7. Sample-Level Analysis\nCaption and grounding paired wins/ties plus baseline-difficulty and target-size groups are in p8_sample_level_analysis.json.\n\n## 8. Failure / Success Cases\nFixed P7 sample IDs 0-9 are retained without reselection. Alpha endpoints have zero max absolute error. Failures remain in metric denominators.\n\n## 9. Scientific Interpretation\nH1 is supported: a weaker residual strength improves utility while retaining geometry gains. H2 is not strongly supported. Anatomy remains directional only.\n\n## 10. Decision for P9\nP8_DIAGNOSIS = OVER_CALIBRATION\nNEXT_STAGE = P9_PRESERVATION_CONSTRAINED_CALIBRATION\nP9 should prioritize stronger/projector-aware preservation and weaker fusion; do not proceed to parcel/pRF yet.\n\nP8_STATUS = COMPLETE\nNEW_TRAINING_STARTED = false\nPARCEL_STAGE_STARTED = false\nPRF_STAGE_STARTED = false\nRETINOTOPY_STAGE_STARTED = false\nP9_RECOMMENDATION = {summary['P9_RECOMMENDATION']}\n''';(O/'p8_report.md').write_text(report)
print(json.dumps(summary,indent=2))
